AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
      - email
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
      - USER_PASSWORD_AUTH
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: APIGatewayAuthNDemo
        schemes:
        - https
        paths:
          /:
            get:
              consumes:
              - application/json
              produces:
              - application/json
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              security:
              - APIGatewayAuthNDemo-authorizer: []
              x-amazon-apigateway-integration:
                type: aws_proxy
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      application/json: |
                        {
                          "message": "Hello"
                        }
                requestTemplates:
                  application/json: |
                    {
                      "statusCode": 200
                    }
                passthroughBehavior: when_no_templates
        securityDefinitions:
          APIGatewayAuthNDemo-authorizer:
            type: apiKey
            name: Authentication
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
              providerARNs:
              - !GetAtt UserPool.Arn
              type: cognito_user_pools
        definitions:
          Empty:
            type: object
            title: Empty Schema
  DescribeInstancesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.7
      Code:
        ZipFile: |
          import json
          import os
          import logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          import boto3
          def handler(event, context):
            try:
              logger.info(json.dumps(event))
              client = boto3.client('ec2')
              response = client.describe_instances()
              logger.info(json.dumps(response))
              return response
            except Exception as e:
              logger.error(e)
              return {}
      Handler: index.handler
      Role: !GetAtt DescribeInstancesFunctionRole.Arn
  DescribeInstancesFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
  InvokeURL:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/v1/"
